-- ============================================================
-- ANCLA — Database Schema
-- Run in Supabase SQL Editor (as a single migration)
-- ============================================================

-- Extensions
create extension if not exists "vector";
create extension if not exists "pg_cron";

-- ============================================================
-- ENUM TYPES
-- ============================================================

create type nivel_riesgo_t   as enum ('bajo', 'medio', 'alto', 'critico');
create type nivel_urgencia_t  as enum ('baja', 'media', 'alta', 'critica');
create type estado_alerta_t   as enum ('nueva', 'en_investigacion', 'resuelta', 'archivada');
create type estado_reporte_t  as enum ('nuevo', 'en_revision', 'procesado', 'archivado');
create type estado_job_t      as enum ('pendiente', 'procesando', 'completado', 'fallido');
create type accion_audit_t    as enum (
  'login', 'logout',
  'ver_alerta', 'ver_reporte',
  'actualizar_estado', 'exportar_reporte'
);

-- ============================================================
-- TABLE: perfiles_agresores
-- Mathematical behavior vectors ONLY. Zero victim data here.
-- ============================================================

create table perfiles_agresores (
  id             uuid           primary key default gen_random_uuid(),
  patron_vector  vector(768)    not null,      -- Google text-embedding-004 dimensions
  plataformas    text[]         not null,      -- ['Instagram', 'Roblox', 'Free Fire']
  tacticas       text[]         not null,      -- ['love_bombing', 'aislamiento', 'solicitud_imagen']
  -- JSONB schema:
  -- {
  --   "franjas": [{"dias_semana": [0-6], "hora_inicio": "HH:MM", "hora_fin": "HH:MM"}],
  --   "zona_horaria_estimada": "America/Mexico_City",
  --   "hora_pico": "HH:MM" | null
  -- }
  horarios       jsonb          not null default '{"franjas":[],"zona_horaria_estimada":"America/Mexico_City","hora_pico":null}',
  nivel_riesgo   nivel_riesgo_t not null default 'medio',
  num_reportes   int            not null default 1,
  created_at     timestamptz    not null default now(),
  updated_at     timestamptz    not null default now()
);

-- HNSW index: works with zero initial data, ideal for a fresh database
create index perfiles_agresores_hnsw_idx
  on perfiles_agresores
  using hnsw (patron_vector vector_cosine_ops)
  with (m = 16, ef_construction = 64);

create index perfiles_agresores_plataformas_idx
  on perfiles_agresores using gin (plataformas);

-- ============================================================
-- TABLE: alertas
-- Auto-generated by AI when patterns are detected.
-- ============================================================

create table alertas (
  id              uuid             primary key default gen_random_uuid(),
  nivel_urgencia  nivel_urgencia_t not null,
  num_victimas    int              not null default 1,
  perfil_id       uuid             references perfiles_agresores(id) on delete set null,
  plataformas     text[]           not null,
  zona_geografica text,
  horarios        jsonb            not null default '{"franjas":[],"zona_horaria_estimada":"America/Mexico_City","hora_pico":null}',
  estado          estado_alerta_t  not null default 'nueva',
  created_at      timestamptz      not null default now(),
  updated_at      timestamptz      not null default now()
);

create index alertas_estado_idx     on alertas (estado);
create index alertas_urgencia_idx   on alertas (nivel_urgencia);
create index alertas_created_idx    on alertas (created_at desc);

-- ============================================================
-- TABLE: reportes_directos
-- Voluntary victim reports. Separated from alertas by design.
-- ============================================================

create table reportes_directos (
  id               uuid             primary key default gen_random_uuid(),
  folio            text             not null unique,  -- 'A-XXXXXX' format
  hash_sha256      text             not null,
  tsa_token        text,            -- RFC 3161 timestamp token (base64), nullable if FreeTSA unavailable
  tsa_timestamp    timestamptz,
  plataforma       text             not null,
  tipo             text             not null,         -- 'sextorsion' | 'grooming' | 'acoso'
  patrones         text[]           not null,
  -- JSONB schema:
  -- {
  --   "plataformas": ["Instagram", "WhatsApp"],
  --   "identificadores": ["@kevindiaz_mx", "5512345678"],  -- any platform identifier
  --   "telefono": "+52 55 1234 5678",                       -- plain text (it's evidence, not PII)
  --   "pais_estimado": "MX",
  --   "horario_contacto": {"hora_inicio": "HH:MM", "hora_fin": "HH:MM"},
  --   "tacticas": ["love_bombing", "aislamiento", "solicitud_imagen"],
  --   "fase_grooming": 1-5,
  --   "descripcion_libre": null | "texto opcional"
  -- }
  perfil_agresor   jsonb            not null,
  -- AES-256-GCM encrypted email. Format: "base64(iv):base64(ciphertext)"
  -- Null if victim chose not to share contact info.
  contacto_cifrado text,
  -- AES-256-GCM encrypted JSON: {nombre, contacto}. Only populated in ruta legal.
  contacto_familiar_cifrado text,
  -- 'privado' = just a record, no one is contacted
  -- 'legal'   = ANCLA agent contacts the family and opens a formal process
  tipo_reporte     text             not null default 'privado'
                     check (tipo_reporte in ('privado', 'legal')),
  -- NULL = not asked (privado), TRUE = implicit (legal — youth provided family contact)
  adulto_al_tanto  boolean          default null,
  alerta_id        uuid             references alertas(id) on delete set null,
  estado           estado_reporte_t not null default 'nuevo',
  created_at       timestamptz      not null default now(),
  updated_at       timestamptz      not null default now()
);

create index reportes_directos_estado_idx   on reportes_directos (estado);
create index reportes_directos_created_idx  on reportes_directos (created_at desc);
create index reportes_directos_alerta_idx   on reportes_directos (alerta_id);

-- ============================================================
-- TABLE: vinculaciones
-- M:M between alertas and reportes_directos with similarity score.
-- ============================================================

create table vinculaciones (
  id              uuid        primary key default gen_random_uuid(),
  alerta_id       uuid        not null references alertas(id) on delete cascade,
  reporte_id      uuid        not null references reportes_directos(id) on delete cascade,
  similitud_score float       not null check (similitud_score >= 0 and similitud_score <= 1),
  confirmada      boolean     not null default false,
  created_at      timestamptz not null default now(),
  unique (alerta_id, reporte_id)
);

-- If the table already exists, run:
-- alter table vinculaciones add column if not exists confirmada boolean not null default false;

-- ============================================================
-- TABLE: jobs_analisis
-- Resilience for long Claude analysis. 15-minute TTL by design.
-- ============================================================

create table jobs_analisis (
  id             uuid         primary key default gen_random_uuid(),
  -- Ephemeral token generated client-side. Never linked to any identity.
  session_token  text         not null,
  estado         estado_job_t not null default 'pendiente',
  -- Input data for processAnalysisJob (stored here so after() can access it)
  -- Schema: { "ocrText": "...", "conversationContext": "..." }
  payload        jsonb        not null,
  resultado      jsonb,       -- null until estado = 'completado'
  error_msg      text,        -- null until estado = 'fallido'
  intentos       int          not null default 0,
  creado_en      timestamptz  not null default now(),
  actualizado_en timestamptz  not null default now(),
  expira_en      timestamptz  not null default (now() + interval '15 minutes')
);

create index jobs_analisis_token_idx  on jobs_analisis (session_token);
create index jobs_analisis_expiry_idx on jobs_analisis (expira_en);

-- Auto-cleanup of expired jobs every 5 minutes
select cron.schedule(
  'cleanup-expired-analysis-jobs',
  '*/5 * * * *',
  $$delete from jobs_analisis where expira_en < now()$$
);

-- ============================================================
-- TABLE: audit_log
-- Insert-only by trigger. Required by LFPDPPP.
-- ============================================================

create table audit_log (
  id           uuid           primary key default gen_random_uuid(),
  agente_id    uuid           not null,   -- auth.users.id; no FK so log survives user deletion
  agente_email text           not null,   -- denormalized for immutability
  accion       accion_audit_t not null,
  recurso_tipo text           not null,
  recurso_id   uuid,
  ip_address   inet,
  user_agent   text,
  created_at   timestamptz    not null default now()
);

create index audit_log_agente_idx  on audit_log (agente_id);
create index audit_log_created_idx on audit_log (created_at desc);

-- Immutability triggers — no UPDATE or DELETE, not even service_role
create or replace function audit_log_immutable()
returns trigger language plpgsql as $$
begin
  raise exception 'audit_log is immutable';
end;
$$;

create trigger audit_log_no_update
  before update on audit_log
  for each row execute function audit_log_immutable();

create trigger audit_log_no_delete
  before delete on audit_log
  for each row execute function audit_log_immutable();

-- ============================================================
-- TABLE: config_plataformas
-- Per-platform similarity thresholds, editable without a deploy.
-- ============================================================

create table config_plataformas (
  id                  uuid        primary key default gen_random_uuid(),
  plataforma          text        not null unique,
  umbral_similitud    float       not null default 0.82
    check (umbral_similitud > 0 and umbral_similitud <= 1),
  max_victimas_alerta int         not null default 3,
  activo              bool        not null default true,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

insert into config_plataformas (plataforma, umbral_similitud) values
  ('Instagram',   0.82),
  ('WhatsApp',    0.82),
  ('TikTok',      0.85),
  ('Discord',     0.85),
  ('Free Fire',   0.88),
  ('Snapchat',    0.85),
  ('Roblox',      0.88),
  ('Minecraft',   0.90);

-- ============================================================
-- TABLE: push_suscripciones
-- Web Push subscriptions for police agents.
-- ============================================================

create table push_suscripciones (
  id          uuid        primary key default gen_random_uuid(),
  agente_id   uuid        not null references auth.users(id) on delete cascade,
  endpoint    text        not null,
  p256dh      text        not null,
  auth_key    text        not null,  -- 'auth' is reserved in PG
  created_at  timestamptz not null default now(),
  unique (agente_id, endpoint)
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table perfiles_agresores  enable row level security;
alter table alertas              enable row level security;
alter table reportes_directos   enable row level security;
alter table vinculaciones        enable row level security;
alter table jobs_analisis        enable row level security;
alter table audit_log            enable row level security;
alter table config_plataformas   enable row level security;
alter table push_suscripciones   enable row level security;

-- Helper: true if the current JWT belongs to a police agent
create or replace function es_agente_policial()
returns bool
language sql stable security definer
as $$
  select coalesce(
    (auth.jwt() -> 'user_metadata' ->> 'rol') = 'policia',
    false
  )
$$;

-- perfiles_agresores: agents read; service_role writes (no INSERT policy = only service_role)
create policy "agentes_ven_perfiles" on perfiles_agresores
  for select using (es_agente_policial());

-- alertas: agents read; agents can update estado; service_role inserts
create policy "agentes_ven_alertas" on alertas
  for select using (es_agente_policial());
create policy "agentes_actualizan_alertas" on alertas
  for update using (es_agente_policial()) with check (es_agente_policial());

-- reportes_directos: agents read; service_role inserts
create policy "agentes_ven_reportes" on reportes_directos
  for select using (es_agente_policial());

-- vinculaciones: agents read
create policy "agentes_ven_vinculaciones" on vinculaciones
  for select using (es_agente_policial());

-- jobs_analisis: no JWT access (service_role only via no policies)

-- audit_log: each agent sees own rows; no updates/deletes (enforced by triggers above)
create policy "agentes_ven_su_audit" on audit_log
  for select using (agente_id = auth.uid());

-- config_plataformas: agents read
create policy "agentes_ven_config" on config_plataformas
  for select using (es_agente_policial());

-- push_suscripciones: agents manage their own
create policy "agentes_ven_sus_suscripciones" on push_suscripciones
  for select using (agente_id = auth.uid());
create policy "agentes_insertan_suscripcion" on push_suscripciones
  for insert with check (agente_id = auth.uid());
create policy "agentes_borran_su_suscripcion" on push_suscripciones
  for delete using (agente_id = auth.uid());

-- ============================================================
-- FUNCTION: incrementar_victimas
-- Atomic num_victimas++ — avoids read-then-write race condition.
-- ============================================================

create or replace function incrementar_victimas(p_alerta_id uuid)
returns void
language sql security definer
as $$
  update alertas
  set num_victimas = num_victimas + 1, updated_at = now()
  where id = p_alerta_id;
$$;

-- ============================================================
-- FUNCTION: es_agente_policial (already defined above)
-- FUNCTION: generar_folio
-- ============================================================

create or replace function generar_folio()
returns text
language sql
as $$
  select 'A-' || upper(substring(md5(gen_random_uuid()::text), 1, 6))
$$;

-- ============================================================
-- FUNCTION: buscar_perfil_similar
-- Cosine similarity search with per-platform configurable threshold.
-- security definer so it runs as owner and can read all rows.
-- ============================================================

create or replace function buscar_perfil_similar(
  p_embedding  vector(768),
  p_plataforma text
)
returns table (
  perfil_id    uuid,
  similitud    float,
  num_reportes int,
  nivel_riesgo nivel_riesgo_t
)
language plpgsql stable security definer
as $$
declare
  v_umbral float := 0.82;
begin
  select umbral_similitud into v_umbral
  from config_plataformas
  where plataforma = p_plataforma and activo = true
  limit 1;

  return query
  select
    pa.id,
    1 - (pa.patron_vector <=> p_embedding) as similitud,
    pa.num_reportes,
    pa.nivel_riesgo
  from perfiles_agresores pa
  where
    pa.plataformas && array[p_plataforma]
    and 1 - (pa.patron_vector <=> p_embedding) >= coalesce(v_umbral, 0.82)
  order by similitud desc
  limit 5;
end;
$$;

-- ============================================================
-- FUNCTION: vincular_reporte_a_alerta
-- Called after a new report is processed. Links to the most
-- recent open alert from the same aggressor profile.
-- ============================================================

create or replace function vincular_reporte_a_alerta(
  p_reporte_id uuid,
  p_perfil_id  uuid,
  p_similitud  float
)
returns void
language plpgsql security definer
as $$
declare
  v_alerta_id uuid;
begin
  select id into v_alerta_id
  from alertas
  where perfil_id = p_perfil_id
    and estado not in ('resuelta', 'archivada')
  order by created_at desc
  limit 1;

  if v_alerta_id is not null then
    insert into vinculaciones (alerta_id, reporte_id, similitud_score)
    values (v_alerta_id, p_reporte_id, p_similitud)
    on conflict (alerta_id, reporte_id) do nothing;

    update reportes_directos
    set alerta_id = v_alerta_id, updated_at = now()
    where id = p_reporte_id;

    update alertas
    set num_victimas = num_victimas + 1, updated_at = now()
    where id = v_alerta_id;
  end if;
end;
$$;

-- ============================================================
-- GRANTS: service_role needs explicit table-level grants
-- (RLS bypass doesn't automatically imply table permission)
-- ============================================================

grant all on table public.perfiles_agresores  to service_role;
grant all on table public.alertas             to service_role;
grant all on table public.reportes_directos   to service_role;
grant all on table public.vinculaciones       to service_role;
grant all on table public.jobs_analisis       to service_role;
grant all on table public.audit_log           to service_role;
grant all on table public.config_plataformas  to service_role;
grant all on table public.push_suscripciones  to service_role;

-- sequences (needed for INSERT on tables with generated IDs)
grant all on all sequences in schema public to service_role;

-- ============================================================
-- REALTIME: enable for police dashboard live updates
-- ============================================================

alter publication supabase_realtime add table alertas;
alter publication supabase_realtime add table reportes_directos;
